#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.elf.C66{1,0,7.4,7
#
image_processing_openmp_evmc6678l.xe66: package/cfg/image_processing_openmp_evmc6678l.xe66.mak

clean::
	-$(RM) package/cfg/image_processing_openmp_evmc6678l.xe66.mak
